### ISSUE TITLE
Not looking for ZIP file

### ISSUE THREAD

**Issue by uBadRequest** [gfek/Hunting-New-Registered-Domains#13]
I'm getting an error that says it can't find the zip file, but it just downloaded it.
Doesn't appear that its actually looking for the zip file?
https://github.com/gfek/Hunting-New-Registered-Domains/blob/d8fadaa88cc004e15f66880328bf87974ba037f2/hnrd.py#L494-L497

**Comment by Humoud** [comment]
@uBadRequest @gfek Looked at the code, the script checks for a `domain-names.txt` file which is the file residing inside the zip file downloaded from whoisds. Now, the zip file is extracted before that check is done. This means that the script is working even if you get that error message.

-------
I am trying to make sense of why such a check would be made, I.e, DATE.txt and I don't mean to speak on behalf of the author, but it would made sense if this check was done initially before downloading the zipfile from whoisds with the following logic:

1. Check if file was downloaded previously
2. If not: download zip file, extract it, **rename extracted file to DATE.txt**
  2.1. process DATE.txt
3. if file was downloaded previously: process DATE.txt
  3.1. process DATE.txt
